### ISSUE TITLE
Test and comment here to provide details

### ISSUE THREAD

**Issue by 2byrds** [GLEIF-IT/vlei-verifier#118]
We tested e2e with large files earlier this week around 146 mb.
It succeeded after couple of config changes but the memory and file storage consumptions seems to be really high for processing a single file. Can you please check what configuration you have on your environment and also try to check how the application works with the configs we have on our environment?
We are carrying out few more tests before we can deploy to Test environment for load testing. We need to check the application performance before we can deploy to test.
Below are the tested configs for the vlei verifier service in our environment
containers:
    - resources:
        limits:
          memory: 3Gi
        requests:
          cpu: 250m
          memory: 128Mi
 
  env:
        - name: KERI_BASER_MAP_SIZE
          value: '1048576000'
        - name: VERIFIER_ENV
          value: production
        - name: VERIFY_ROOT_OF_TRUST
          value: 'False'

Can you please look into this and let me know.

**Comment by ronakseth96** [comment]
Sure @2byrds. I'll take a look into this and update you.

**Comment by 2byrds** [comment]
Thank you @ronakseth96 I have also followed up with a few additional requests for details. If you need further information feel free to respond to the email and add any additional information here.

**Comment by ronakseth96** [comment]
Sounds good, thank you!

**Comment by pgovindeba** [comment]
@2byrds  , @ronakseth96  :  We use veli-verifier -0.0.3 and reg-pilot-api -01.0 versions. The usage is high when the file is processed and it goes down shortly after that. This high usage makes the application pods in openshift crash.

**Comment by 2byrds** [comment]
@pgovindeba thank you for the details. I met with @ronakseth96 this morning and we'll respond with guidance in a day or so.

**Comment by 2byrds** [comment]
I was able to get the verifier to complete a successful upload of 300MB when the memory limit was set to 2GB. I was able to get the verifier to crash with a 500MB file upload, when limiting the container to 2GB of memory. If i set the limit to 3GB of memory for a single user, single upload, then it succeeded despite running up to the 3GB limit. After the upload succeeded, the memory usage fell to roughly 400MB for a short time then to 25MB. I then left the verifier running and with the same user i uploaded a 500MB report to the verifier again. It once again ran up to the 3GB memory limit during upload, ie. 100% of memory usage, but did not crash and completed the upload successfully. I need to fix a regression in the test harness so i can run with multiple users, as the next phase of testing.

**Comment by 2byrds** [comment]
Documenting my docker-compose settings that succeeded with a 500MB upload with 3GB memory limit:
```
reg-pilot-api:
    image: gleif/reg-pilot-api:0.1.0
    ports:
      - 8000:8000
    environment:
      - KERI_BASER_MAP_SIZE=500000000
      - ENABLE_CORS=true
      - VLEI_VERIFIER=http://vlei-verifier:7676
      - FILER_REPORTS=http://vlei-verifier:7676/reports/
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://reg-pilot-api:8000/ping"]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s

  vlei-verifier:
    image: gleif/vlei-verifier:0.0.3
    container_name: vlei-verifier
    hostname: vlei-verifier
    depends_on:
      - vlei-server
      - witness-demo
    ports:
      - 7676:7676
    deploy:
      resources:
        limits:
          memory: 3G
    environment:
      - KERI_BASER_MAP_SIZE=1000000000
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://vlei-verifier:7676/health"]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
```

**Comment by ronakseth96** [comment]
Based on my testing, here are the observations:


Test Case | Memory Limit | Reservations (CPU/Memory) | File Size | Peak Memory Usage | Upload Time | Total API Test Time | Verifier Service
-- | -- | -- | -- | -- | -- | -- | --
Test 1 | 3G | 0.25 CPU / 128M Memory | 150M | 1.71G (57%) | - | - | Running
Test 2 | 2G | 0.25 CPU / 128M Memory | 300M | 2G (100%) | 75.4s | 2m 23s | Running
Test 3 | 3G | 0.25 CPU / 128M Memory | 300M | 2.99G (~100%) | 61.6s | 2m 3s | Running
Test 4 | 2G | 0.25 CPU / 128M Memory | 500M | 2G (100%) | 62.8s | 2m 23s | Crashed
Test 5 | 3G | 0.25 CPU / 128M Memory | 500M | 3G (100%) | 139.2s | - | Crashed

- 500MB file uploads consistently caused the verifier to crash at both 2G and 3G memory limits, likely due to Out of Memory (OOM) conditions.
- 300MB file uploads were successful at both 2G and 3G limits, though increasing the memory limit to 3G improved the upload time (from 75.4s → 61.6s).

**Comment by 2byrds** [comment]
Thank you @ronakseth96 . I ran 10 rounds of 150MB uploads with configuration that matches @pgovindeba settings and they all succeeded:
```
  reg-pilot-api:
    image: gleif/reg-pilot-api:0.1.0
    ports:
      - 8000:8000
    environment:
      - ENABLE_CORS=true
      - VLEI_VERIFIER=http://vlei-verifier:7676
      - FILER_REPORTS=http://vlei-verifier:7676/reports/
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 128M
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://reg-pilot-api:8000/ping"]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s

  vlei-verifier:
    image: gleif/vlei-verifier:0.0.3
    container_name: vlei-verifier
    hostname: vlei-verifier
    depends_on:
      - vlei-server
      - witness-demo
    ports:
      - 7676:7676
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 128M
    environment:
      - KERI_BASER_MAP_SIZE=1048576000
      - VERIFIER_ENV=production
      - VERIFY_ROOT_OF_TRUST=False
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://vlei-verifier:7676/health"]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
```
